
DROP TABLE news IF EXISTS;
DROP TABLE news_type IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE news_type
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name_type   VARCHAR(255)            NOT NULL,
    color_type  VARCHAR(255)            NOT NULL
);

CREATE TABLE news
(
  id                    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name                  VARCHAR(255)            NOT NULL,
  description_short     VARCHAR(255)            NOT NULL,
  description_full      VARCHAR(255)            NOT NULL,
  type_news_id          INTEGER                 NOT NULL,
  FOREIGN KEY (type_news_id) REFERENCES news_type (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX news_unique_name_description_short
    ON news (name, description_short);



